development:
  cloud_name: CLOUDINARY_CLOUD_NAME
  api_key: CLOUDINARY_API_KEY
  api_secret: CLOUDINARY_API_SECRET
  enhance_image_tag: true
  static_file_support: false

test:
  cloud_name: CLOUDINARY_CLOUD_NAME
  api_key: CLOUDINARY_API_KEY
  api_secret: CLOUDINARY_API_SECRET
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: CLOUDINARY_CLOUD_NAME
  api_key: CLOUDINARY_API_KEY
  api_secret: CLOUDINARY_API_SECRET
  enhance_image_tag: true
  static_file_support: true
