development:
  cloud_name: "m-lague"
  api_key: "495462367189913"
  api_secret: "vVjOCWXLhWZaDt0CPe1PMfXycKc"
  enhance_image_tag: true
  static_file_support: false

test:
  cloud_name: "m-lague"
  api_key: "495462367189913"
  api_secret: "vVjOCWXLhWZaDt0CPe1PMfXycKc"
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: "m-lague"
  api_key: "495462367189913"
  api_secret: "vVjOCWXLhWZaDt0CPe1PMfXycKc"
  enhance_image_tag: true
  static_file_support: true
